<template>
  <div>
  <table border="1" width="100%" cellspacing="0" cellpadding="0" class="table">
    <tbody @mouseover="hoverX" @mouseout="hoverXOut">
      <tr>
    <th colspan="2">韻母 \ 聲母</th>
    <th>-</th>
    <th>ㄅ<br>
      b</th>
    <th>ㄆ<br>
      p</th>
    <th>ㄇ<br>
      m</th>
    <th>ㄈ<br>
      f</th>
    <th>ㄉ<br>
      d</th>
    <th>ㄊ<br>
      t</th>
    <th>ㄋ<br>
      n</th>
    <th>ㄌ<br>
      l</th>
    <th>ㄍ<br>
      g</th>
    <th>ㄎ<br>
      k</th>
    <th>ㄏ<br>
      h</th>
    <th>ㄐ<br>
      j</th>
    <th>ㄑ<br>
      q</th>
    <th>ㄒ<br>
      x</th>
    <th>ㄓ<br>
      zh</th>
    <th>ㄔ<br>
      ch</th>
    <th>ㄕ<br>
      sh</th>
    <th>ㄖ<br>
      r</th>
    <th>ㄗ<br>
      z</th>
    <th>ㄘ<br>
      c</th>
    <th>ㄙ<br>
      s</th>
  </tr>
  <tr>
    <th>ㄚ</th>
    <th>a</th>
    <td>a</td>
    <td>ba</td>
    <td>pa</td>
    <td>ma</td>
    <td>fa</td>
    <td>da</td>
    <td>ta</td>
    <td>na</td>
    <td>la</td>
    <td>ga</td>
    <td>ka</td>
    <td>ha</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zha</td>
    <td>cha</td>
    <td>sha</td>
    <td></td>
    <td>za</td>
    <td>ca</td>
    <td>sa</td>
  </tr>
  <tr>
    <th>ㄛ</th>
    <th>o</th>
    <td>o</td>
    <td>bo</td>
    <td>po</td>
    <td>mo</td>
    <td>fo</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄜ</th>
    <th>e</th>
    <td>e</td>
    <td></td>
    <td></td>
    <td>me</td>
    <td></td>
    <td>de</td>
    <td>te</td>
    <td>ne</td>
    <td>le</td>
    <td>ge</td>
    <td>ke</td>
    <td>he</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhe</td>
    <td>che</td>
    <td>she</td>
    <td>re</td>
    <td>ze</td>
    <td>ce</td>
    <td>se</td>
  </tr>
  <tr>
    <th>ㄝ</th>
    <th>E</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄦ</th>
    <th>er</th>
    <td>er</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄞ</th>
    <th>ai</th>
    <td>ai</td>
    <td>bai</td>
    <td>pai</td>
    <td>mai</td>
    <td></td>
    <td>dai</td>
    <td>tai</td>
    <td>nai</td>
    <td>lai</td>
    <td>gai</td>
    <td>kai</td>
    <td>hai</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhai</td>
    <td>chai</td>
    <td>shai</td>
    <td></td>
    <td>zai</td>
    <td>cai</td>
    <td>sai</td>
  </tr>
  <tr>
    <th>ㄟ</th>
    <th>ei</th>
    <td>ei</td>
    <td>bei</td>
    <td>pei</td>
    <td>mei</td>
    <td>fei</td>
    <td>dei</td>
    <td></td>
    <td>nei</td>
    <td>lei</td>
    <td>gei</td>
    <td></td>
    <td>hei</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhei</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zei</td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄠ</th>
    <th>ao</th>
    <td>ao</td>
    <td>bao</td>
    <td>pao</td>
    <td>mao</td>
    <td></td>
    <td>dao</td>
    <td>tao</td>
    <td>nao</td>
    <td>lao</td>
    <td>gao</td>
    <td>kao</td>
    <td>hao</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhao</td>
    <td>chao</td>
    <td>shao</td>
    <td>rao</td>
    <td>zao</td>
    <td>cao</td>
    <td>sao</td>
  </tr>
  <tr>
    <th>ㄡ</th>
    <th>ou</th>
    <td>ou</td>
    <td></td>
    <td>pou</td>
    <td>mou</td>
    <td>fou</td>
    <td>dou</td>
    <td>tou</td>
    <td>nou</td>
    <td>lou</td>
    <td>gou</td>
    <td>kou</td>
    <td>hou</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhou</td>
    <td>chou</td>
    <td>shou</td>
    <td>rou</td>
    <td>zou</td>
    <td>cou</td>
    <td>sou</td>
  </tr>
  <tr>
    <th>ㄢ</th>
    <th>an</th>
    <td>an</td>
    <td>ban</td>
    <td>pan</td>
    <td>man</td>
    <td>fan</td>
    <td>dan</td>
    <td>tan</td>
    <td>nan</td>
    <td>lan</td>
    <td>gan</td>
    <td>kan</td>
    <td>han</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhan</td>
    <td>chan</td>
    <td>shan</td>
    <td>ran</td>
    <td>zan</td>
    <td>can</td>
    <td>san</td>
  </tr>
  <tr>
    <th>ㄣ</th>
    <th>en</th>
    <td>en</td>
    <td>ben</td>
    <td>pen</td>
    <td>men</td>
    <td>fen</td>
    <td></td>
    <td></td>
    <td>nen</td>
    <td></td>
    <td>gen</td>
    <td>ken</td>
    <td>hen</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhen</td>
    <td>chen</td>
    <td>shen</td>
    <td>ren</td>
    <td>zen</td>
    <td>cen</td>
    <td>sen</td>
  </tr>
  <tr>
    <th>ㄤ</th>
    <th>ang</th>
    <td>ang</td>
    <td>bang</td>
    <td>pang</td>
    <td>mang</td>
    <td>fang</td>
    <td>dang</td>
    <td>tang</td>
    <td>nang</td>
    <td>lang</td>
    <td>gang</td>
    <td>kang</td>
    <td>hang</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhang</td>
    <td>chang</td>
    <td>shang</td>
    <td>rang</td>
    <td>zang</td>
    <td>cang</td>
    <td>sang</td>
  </tr>
  <tr>
    <th>ㄥ</th>
    <th>eng</th>
    <td></td>
    <td>beng</td>
    <td>peng</td>
    <td>meng</td>
    <td>feng</td>
    <td>deng</td>
    <td>teng</td>
    <td>neng</td>
    <td>leng</td>
    <td>geng</td>
    <td>keng</td>
    <td>heng</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zheng</td>
    <td>cheng</td>
    <td>sheng</td>
    <td>reng</td>
    <td>zeng</td>
    <td>ceng</td>
    <td>seng</td>
  </tr>
  <tr>
    <th>ㄨㄥ</th>
    <th>ong</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>dong</td>
    <td>tong</td>
    <td>nong</td>
    <td>long</td>
    <td>gong</td>
    <td>kong</td>
    <td>hong</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhong</td>
    <td>chong</td>
    <td></td>
    <td>rong</td>
    <td>zong</td>
    <td>cong</td>
    <td>song</td>
  </tr>
  <tr>
    <th>ㄧ</th>
    <th>i</th>
    <td>yi</td>
    <td>bi</td>
    <td>pi</td>
    <td>mi</td>
    <td></td>
    <td>di</td>
    <td>ti</td>
    <td>ni</td>
    <td>li</td>
    <td></td>
    <td></td>
    <td></td>
    <td>ji</td>
    <td>qi</td>
    <td>xi</td>
    <td>zhi</td>
    <td>chi</td>
    <td>shi</td>
    <td>ri</td>
    <td>zi</td>
    <td>ci</td>
    <td>si</td>
  </tr>
  <tr>
    <th>ㄧㄚ</th>
    <th>ia</th>
    <td>ya</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>lia</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jia</td>
    <td>qia</td>
    <td>xia</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄧㄠ</th>
    <th>iao</th>
    <td>yao</td>
    <td>biao</td>
    <td>piao</td>
    <td>miao</td>
    <td></td>
    <td>diao</td>
    <td>tiao</td>
    <td>niao</td>
    <td>liao</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jiao</td>
    <td>qiao</td>
    <td>xiao</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄧㄝ</th>
    <th>ie</th>
    <td>ye</td>
    <td>bie</td>
    <td>pie</td>
    <td>mie</td>
    <td></td>
    <td>die</td>
    <td>tie</td>
    <td>nie</td>
    <td>lie</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jie</td>
    <td>qie</td>
    <td>xie</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄧㄡ</th>
    <th>iu</th>
    <td>you</td>
    <td></td>
    <td></td>
    <td>miu</td>
    <td></td>
    <td>diu</td>
    <td></td>
    <td>niu</td>
    <td>liu</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jiu</td>
    <td>qiu</td>
    <td>xiu</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄧㄢ</th>
    <th>ian</th>
    <td>yan</td>
    <td>bian</td>
    <td>pian</td>
    <td>mian</td>
    <td></td>
    <td>dian</td>
    <td>tian</td>
    <td>nian</td>
    <td>lian</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jian</td>
    <td>qian</td>
    <td>xian</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄧㄣ</th>
    <th>in</th>
    <td>yin</td>
    <td>bin</td>
    <td>pin</td>
    <td>min</td>
    <td></td>
    <td></td>
    <td></td>
    <td>nin</td>
    <td>lin</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jin</td>
    <td>qin</td>
    <td>xin</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄧㄤ</th>
    <th>iang</th>
    <td>yang</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>niang</td>
    <td>liang</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jiang</td>
    <td>qiang</td>
    <td>xiang</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄧㄥ</th>
    <th>ing</th>
    <td>ying</td>
    <td>bing</td>
    <td>ping</td>
    <td>ming</td>
    <td></td>
    <td>ding</td>
    <td>ting</td>
    <td>ning</td>
    <td>ling</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jing</td>
    <td>qing</td>
    <td>xing</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄩㄥ</th>
    <th>iong</th>
    <td>yong</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>jiong</td>
    <td>qiong</td>
    <td>xiong</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄨ</th>
    <th>u</th>
    <td>wu</td>
    <td>bu</td>
    <td>pu</td>
    <td>mu</td>
    <td>fu</td>
    <td>du</td>
    <td>tu</td>
    <td>nu</td>
    <td>lu</td>
    <td>gu</td>
    <td>ku</td>
    <td>hu</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhu</td>
    <td>chu</td>
    <td>shu</td>
    <td>ru</td>
    <td>zu</td>
    <td>cu</td>
    <td>su</td>
  </tr>
  <tr>
    <th>ㄨㄚ</th>
    <th>ua</th>
    <td>wa</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>gua</td>
    <td>kua</td>
    <td>hua</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhua</td>
    <td>chua</td>
    <td>shua</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄨㄛ</th>
    <th>uo</th>
    <td>wo</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>duo</td>
    <td>tuo</td>
    <td>nuo</td>
    <td>luo</td>
    <td>guo</td>
    <td>kuo</td>
    <td>huo</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhuo</td>
    <td>chuo</td>
    <td>shuo</td>
    <td>ruo</td>
    <td>zuo</td>
    <td>cuo</td>
    <td>suo</td>
  </tr>
  <tr>
    <th>ㄨㄞ</th>
    <th>uai</th>
    <td>wai</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>guai</td>
    <td>kuai</td>
    <td>huai</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhuai</td>
    <td>chuai</td>
    <td>shuai</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄨㄟ</th>
    <th>ui</th>
    <td>wei</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>dui</td>
    <td>tui</td>
    <td></td>
    <td></td>
    <td>gui</td>
    <td>kui</td>
    <td>hui</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhui</td>
    <td>chui</td>
    <td>shui</td>
    <td>rui</td>
    <td>zui</td>
    <td>cui</td>
    <td>sui</td>
  </tr>
  <tr>
    <th>ㄨㄢ</th>
    <th>uan</th>
    <td>wan</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>duan</td>
    <td>tuan</td>
    <td>nuan</td>
    <td>luan</td>
    <td>guan</td>
    <td>kuan</td>
    <td>huan</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhuan</td>
    <td>chuan</td>
    <td>shuan</td>
    <td>ruan</td>
    <td>zuan</td>
    <td>cuan</td>
    <td>suan</td>
  </tr>
  <tr>
    <th>ㄨㄣ</th>
    <th>un</th>
    <td>wen</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>dun</td>
    <td>tun</td>
    <td>nun</td>
    <td>lun</td>
    <td>gun</td>
    <td>kun</td>
    <td>hun</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhun</td>
    <td>chun</td>
    <td>shun</td>
    <td>run</td>
    <td>zun</td>
    <td>cun</td>
    <td>sun</td>
  </tr>
  <tr>
    <th>ㄨㄤ</th>
    <th>uang</th>
    <td>wang</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>guang</td>
    <td>kuang</td>
    <td>huang</td>
    <td></td>
    <td></td>
    <td></td>
    <td>zhuang</td>
    <td>chuang</td>
    <td>shuang</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄨㄥ</th>
    <th>ueng</th>
    <td>weng</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄩ</th>
    <th>U</th>
    <td>yU</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>nU</td>
    <td>lU</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jU</td>
    <td>qU</td>
    <td>xU</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄩㄝ</th>
    <th>Ue</th>
    <td>yUe</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>nUe</td>
    <td>lUe</td>
    <td></td>
    <td></td>
    <td></td>
    <td>jUe</td>
    <td>qUe</td>
    <td>xUe</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄩㄢ</th>
    <th>Uan</th>
    <td>yUan</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>jUan</td>
    <td>qUan</td>
    <td>xUan</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th>ㄩㄣ</th>
    <th>Un</th>
    <td>yUn</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>jUn</td>
    <td>qUn</td>
    <td>xUn</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
  <tr>
    <th colspan="2">韻母 \ 聲母</th>
    <th>-</th>
    <th>b<br>
      ㄅ</th>
    <th>p<br>
      ㄆ</th>
    <th>m<br>
      ㄇ</th>
    <th>f<br>
      ㄈ</th>
    <th>d<br>
      ㄉ</th>
    <th>t<br>
      ㄊ</th>
    <th>n<br>
      ㄋ</th>
    <th>l<br>
      ㄌ</th>
    <th>g<br>
      ㄍ</th>
    <th>k<br>
      ㄎ</th>
    <th>h<br>
      ㄏ</th>
    <th>j<br>
      ㄐ</th>
    <th>q<br>
      ㄑ</th>
    <th>x<br>
      ㄒ</th>
    <th>zh<br>
      ㄓ</th>
    <th>ch<br>
      ㄔ</th>
    <th>sh<br>
      ㄕ</th>
    <th>r<br>
      ㄖ</th>
    <th>z<br>
      ㄗ</th>
    <th>c<br>
      ㄘ</th>
    <th>s<br>
      ㄙ</th>
  </tr>
</tbody>
</table>
<i>Please zoom page to fit your screen.</i>
  </div>  
</template>

<script>
export default {
  name: "z2pTable",
  props: {},
  methods: {
    hoverX: function(event) {
      let className = event.target.className;
      if (className === "") {
        return;
      }
      let selectedColumns = document.querySelectorAll("td." + className);
      for (let i = 0; i < selectedColumns.length; i++) {
        selectedColumns[i].classList.add("selected");
      }
    },
    hoverXOut: function(event) {
      let className = event.target.className;
      if (className === "") {
        return;
      }
      let className_fix = className.replace(" ", ".");
      let selectedColumns = document.querySelectorAll("td." + className_fix);
      for (let i = 0; i < selectedColumns.length; i++) {
        selectedColumns[i].classList.remove("selected");
      }
    }
  },
  mounted: function() {
    let allTd = document.querySelectorAll("td");
    for (let i = 0; i < allTd.length; i++) {
      let aa = i % 22;
      allTd[i].classList.add("td" + aa);
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
table {
  table-layout: fixed;
  border-collapse: collapse;
}
th {
  background-color: black;
  color: white;
}
tr {
  color: #888;
}
tr:hover {
  background-color: #a3d4404a;
  color: #000;
}
td {
  border-top: 0px;
  border-right: 1px solid #e0e0e0;
  border-bottom: 1px solid #e0e0e0;
  border-left: 0px;
}
td:hover {
  font-weight: bold;
  background-color: #b1e415;
}
.selected {
  color: #000;
  background-color: #a3d4404a;
}
</style>